[package]
name = "reth-scroll"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-cli-util.workspace = true
reth-node-builder = { workspace = true, features = ["scroll"] }
reth-provider = { workspace = true, features = ["scroll"] }
reth-scroll-cli.workspace = true
reth-scroll-node.workspace = true

# misc
clap = { workspace = true, features = ["derive", "env"] }

[features]
scroll = []

[[bin]]
name = "reth-scroll"
path = "src/main.rs"

